name: Deploy
on:
  push:
    tags:
      - '*'
  workflow_call: # Make this workflow callable from other workflows
  workflow_dispatch: # Make this workflow runnable on github

concurrency: deploy

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
  deploy:
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy production -o hostname=${{ secrets.HOSTNAME }} -o port=${{ secrets.SSH_PORT }} --revision="${{ github.sha }}"
